### ISSUE TITLE
Updates to v13 Documentation

### ISSUE THREAD

**Issue by mikkimichaelis** [j3k0/cordova-plugin-purchase-documentation#7]
Hi @j3k0!

I'm starting a converssion from 11 -> 13 and I've noticed some out of date v13 documentation.  Starting with in the micro example, there are references to CdvPurchase.CONSUMABLE which now seem to be CdvPurchase.ProductType.CONSUMABLE.

I'm going to fork this repo and make updates as I find them.  I just didn't want to duplicate an already in process effort.  And of course ask for any enlightment you can give me on this process.

Thanks,
Mikki

**Comment by j3k0** [comment]
Thanks. Please submit your pull requests!
